-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 17:55:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Directors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Films` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `director_id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`, `director_id`),
  INDEX `fk_Films_Directors1_idx` (`director_id` ASC) VISIBLE,
  CONSTRAINT `fk_Films_Directors1`
    FOREIGN KEY (`director_id`)
    REFERENCES `mydb`.`Directors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Films_have_Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Films_have_Genres` (
  `Films_id` INT NOT NULL,
  `Genres_id` INT NOT NULL,
  PRIMARY KEY (`Films_id`, `Genres_id`),
  INDEX `fk_Films_has_Genres_Genres1_idx` (`Genres_id` ASC) VISIBLE,
  INDEX `fk_Films_has_Genres_Films_idx` (`Films_id` ASC) VISIBLE,
  CONSTRAINT `fk_Films_has_Genres_Films`
    FOREIGN KEY (`Films_id`)
    REFERENCES `mydb`.`Films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_has_Genres_Genres1`
    FOREIGN KEY (`Genres_id`)
    REFERENCES `mydb`.`Genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
